name: Run Prester Tests
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  pester-test:
    name: Run Pester Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Pester Tests
        shell: pwsh
        run: Test-Path Tests/Results/TestResults.xml | Should -Be $true
      - name: Run Tests.ps1
        shell: pwsh
        run: |
          Invoke-Pester ./Tests/ -PassThru -OutputFile ./Tests/Results/TestResults.xml
